### ISSUE TITLE
Latest snap update destroyed all databases

### ISSUE THREAD

**Issue by Lesterpig** [apache/couchdb-pkg#54]
## Expected Behavior

Snaps are updated automatically. One would expect that its data is preserved by the update operation.

## Current Behavior

All databases were destroyed by the snap refresh operation during the night.

```
$ snap changes
Identifiant  État  Descendance          Prêt                 Résumé
116          Done  today at 05:21 CEST  today at 05:21 CEST  Actualiser automatiquement le paquet Snap "couchdb"
```

I'm unable to read the full log of operations, as `snap logs couchdb -n=all` stops after the first server shutdown. This might be an issue with snap itself.

## Steps to Reproduce (for bugs)

I was unable to reproduce this bug, as previous snap versions are not listed.

## Context

This bug triggered itself without any action due to the auto-refresh policy of snap.
This is not a critical problem for me, my data is safe thanks to replication. But I believe this is an important issue that might affect several people.

## Your Environment

* Version used: snap 2.3.1
* Operating System and version: desktop Ubuntu 19.04

**Comment by willholley** [comment]
yikes. I don't know anything about snap but if you're able to see how https://github.com/apache/couchdb-pkg/pull/53 might have triggered what you observed I'm sure it would be helpful.

**Comment by Lesterpig** [comment]
This looks like the data directory changed in this latest update (from `${SNAP_DATA}/data` to `${SNAP_COMMON}/data`). I'm not used to snap either, but this should be the reason of this data loss, snap removing all data prior to refresh and creating a pristine new data folder?

https://github.com/apache/couchdb-pkg/pull/53/files#diff-663c3db1891d3deaaf1df297870d124bR19

**Comment by wohali** [comment]
Hi @Lesterpig ,

Sorry about this.

Your data should still be there -- the previous snap put the data in the wrong place, and we corrected it just now

You need to look inside of ${SNAP_COMMON} now instead of ${SNAP_DATA}. It *should* be possible to move the data from one to the other and restore data, but if not, we sincerely apologise, you got caught in our testing process.

Our migration process for the very short lived versions 3 or 4 may have issues.

@sklassen can you assist here?

**Comment by Lesterpig** [comment]
No worries @wohali I already retrieved the data thanks to replication :)
If the issue is solved in snap version 5, then I believe this issue could be closed; but maybe a small notice should be published for other potential "victims"? :smile:

**Comment by wohali** [comment]
@Lesterpig Thanks for that. Unfortunately there's no easy way to release notices for snaps - other than this issue.

Version 5 should be the version you just got installed.

Let's wait to see what @sklassen has to say.

**Comment by sklassen** [comment]
Hi,

The above is correct. The couchdb (3) snap was using
/var/snap/couchdb/current while it should have been using
/var/snap/couchdb/common; going forth, new snap versions from (5) onwards
will not need to be manually moved.

If you've successfully restored via replication you might consider removing
the /var/snap/couchdb/current/data directory, otherwise it will be
duplicated in a SNAP_DATA subdiretory for each revision.

If you can't recover your data by other means, then "sudo snap couchdb
revert" will restore your configuration and data directory. You should then
move the 'data' directory from 'current' to 'common' before the next snap
refresh.

I hope that helps

Simon

**Comment by Lesterpig** [comment]
It seems I was one of the only few that experienced this issue. Time to close I think, thanks for your help :)
