### ISSUE TITLE
Snap Package Update

### ISSUE THREAD

**Issue by theArianit** [apache/couchdb-pkg#73]
What's the roadmap for CouchDB with Snap? Will it be updated to the newest version?

**Comment by wohali** [comment]
Sure, we can get that done. I'll put it on today's list.

**Comment by theArianit** [comment]
wow, that was unexpected fast. thank you. But just out of curiosity, why was the CouchDB version 2.3 as snap instead of the newest 3.1.1?

**Comment by wohali** [comment]
@theArianit Because there are breaking changes in 3.x vs 2.x, and we thought it'd be safest for continuity this way.

Arguably it's probably time to put 3.x on latest, but you tell me how the migration goes first.

You can pull the 3.x version from the `latest/candidate` or `3.x` channels on the Snapcraft store.

**Comment by theArianit** [comment]
I just found out that you can pick the version on the snap store. 
But I have a fresh system, and I am not upgrading, so I can't give you any feedback on migration.
